---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: {app_name}
    release: "1.1.0"
    env: {env}
  name: {app_name}
  namespace: {ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {app_name}
      release: "1.1.0"
      env: {env}  
  strategy: 
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {app_name}
        release: "1.1.0"
        env: {env}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: ssai-{env}-config-map
        image: {image}
        imagePullPolicy: Always
        name: {app_name}
        ports:
        - containerPort: 80
      nodeSelector:
        env: {nodename}
        platform: apps
      tolerations:
      - key: "platform"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
      - key: "env"
        operator: "Equal"
        value: {nodename}
        effect: "NoSchedule"
status: {}

---

apiVersion: v1
kind: Service
metadata: 
  labels:
    app: {app_name}
    env: {env}
    release: "1.1.0"
  name: {app_name}
  namespace: {ns}
spec:
  externalTrafficPolicy: Cluster 
  ports:  
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {app_name}
    env: {env}
    release: "1.1.0"
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
